---
version: "2.0"

services:
  web:
    image: user994455/ubuntu-base:0.2
    env:
      - sshport=22000
      - pubkey="your_public_ssh_key_here"
    expose:
      - port: 22000
        as: 22000
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 20Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 20

deployment:
  web:
    dcloud:
      profile: web
      count: 1
